services:

  attendancedb:
    image: mysql
    container_name: attendancedb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]   #this command is for mysql only, for other databases refer documentation
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: attendancedb
    extends:
      file: common-config.yml
      service: network-deploy-service

networks:
  vision-network:
