spring:
  application:
    name: VisionIdBackend
  datasource:
    url: jdbc:mysql://localhost:3306/attendancedb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true # “First let Hibernate create tables, then run data.sql.”
    show-sql: true
  sql:
    init:
      mode: always


#  So yes —
#  @Entity + ddl-auto: update = automatic table creation.